CREATE TABLE EXTRATO (
	ID INTEGER NOT NULL,
	NUMEROCONTA VARCHAR(100) NOT NULL,
	NOMETITULAR VARCHAR(100) NOT NULL,
	CONSTRAINT EXTRATO_PK PRIMARY KEY (ID)
);

CREATE TABLE "TIPOREGISTRO"  (
		  "ID" INTEGER NOT NULL , 
		  "TIPO" VARCHAR(7 OCTETS) NOT NULL,
		 	CONSTRAINT EXTRATO_PK PRIMARY KEY (ID));


CREATE TABLE "REGISTRO"  (
		  "ID" INTEGER NOT NULL , 
		  "VALOR" DECIMAL(5,0) , 
		  "TIPOID" INTEGER NOT NULL , 
		  "EXTRATOID" INTEGER NOT NULL,
		 CONSTRAINT "REGISTRO_PK" PRIMARY KEY
		("ID"),
		 CONSTRAINT "REGISTRO_EXTRATO_FK" FOREIGN KEY
		("EXTRATOID")
	REFERENCES "EXTRATO"
		("ID"),
	 CONSTRAINT "REGISTRO_TIPO_FK" FOREIGN KEY
		("TIPOID")
	REFERENCES "TIPOREGISTRO"
		("ID")
		);

